# Description: change the library path for different platforms
#
#      Author: Ou Niansen <ouyuyuan@lasg.iap.ac.cn>
#        Date: 2015-03
#
NLIB = -L/WORK/home/qhyc1/software/lib -lnetcdf -lnetcdff
ILIB = -I/WORK/home/qhyc1/software/include

FC   =  ifort
# FF   = -O2 -r8 -no-vec -fpe0 -traceback
# FF   = -O2 -r8 -no-vec
 FF   = -O3 -r8
# FF   = -O2 -r8 -no-vec
# FF   = -O2 -no-vec

#EXE = main
#BJS = basic_mod.o io_mod.o integrate_mod.o main.o
EXE  = main
OBJS = mod_type.o netcdf_io_mod.o main.o

.PHONY: all compile run clean

# need this 'empty' line to avoid some problem when 'make'
.SUFFIXES:

.SUFFIXES: .f90 .o

all: clean compile run

compile: $(OBJS)
	$(FC) $(FF) $(OBJS) -o $(EXE) $(NLIB) $(ILIB)

.f90.o:
	$(FC) $(FF) -c $< $(NLIB) $(ILIB)

run:
	./$(EXE)

clean:
	rm -f *.mod *.o *.out $(EXE)
