
# .bash_profile will source when log in, while .bashrc not.
# These lines make sure I only have to maintain the environments 
# in the .bashrc file

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
